/****** Script for SelectTopNRows command from SSMS  ******/
SELECT [type]
      ,[amount]
      ,[Organization_ID]
      ,[oldbalanceOrg]
      ,[newbalanceOrig]
      ,[nameDest]
      ,[oldbalanceDest]
      ,[newbalanceDest]
      ,[isFraud]
  FROM [FRAUD_COSTOMER_ANALYSIS].[dbo].[Financial Dataset]